// AUTO-GENERATED by generate-plugin-config.js - DO NOT EDIT
export const pluginAliasPaths: Record<string, string> = {
  '@mdview/plugin-pdf': '../plugin-pdf/src/index.tsx',
  '@mdview/plugin-images': '../plugin-images/src/index.tsx',
  '@mdview/plugin-editor': '../plugin-editor/src/index.tsx',
};
