// AUTO-GENERATED by generate-plugin-config.js — DO NOT EDIT
// Source: packages/plugins.json
// These are relative paths from packages/core/ to each plugin's src/ directory.

export const pluginAliasPaths: Record<string, string> = {
  '@mdview/plugin-pdf': '../plugin-pdf/src',
  '@mdview/plugin-images': '../plugin-images/src',
  '@mdview/plugin-editor': '../plugin-editor/src',
};
