// AUTO-GENERATED by generate-plugin-config.js - DO NOT EDIT
export const pluginAliasPaths: Record<string, string> = {
  '@mdview/plugin-pdf': 'packages/plugin-pdf/src/index.tsx',
  '@mdview/plugin-images': 'packages/plugin-images/src/index.tsx',
  '@mdview/plugin-editor': 'packages/plugin-editor/src/index.tsx',
};
